name: First workflow
on: workflow_dispatch
jobs:
  first-job:
  runs-on: ubuntu-latest
  steps:
  - name: print greetings
    run: echo "Welcome to first workflow"
  - name: print goodbye
    run: echo "Good bye and all the best"
